#!/bin/bash


######## CHECK (system_info.sh -c) 
if [ $1 == "check" ]
    then


    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_DISK_CAPACITY_status=0


    ######## CHECK_DISK_CAPACITY
    ######## DF
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_DISK_CAPACITY (# $DF $DF_p)" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT

    if [ ! -f "$DF" ]
	then
	$PRINT "$MSG_MISSING_COMMAND $DF" >> $OUTPUT
	$PRINT "$MSG_NEED_PACKAGE $DF_package" >> $OUTPUT
	let CHECK_DISK_CAPACITY_status=1
	
	else
	$DF $DF_p >> $OUTPUT
	check_rv_output CHECK_DISK_CAPACITY_status
    fi

    $PRINTE "\n\n" >> $OUTPUT

fi
