#!/bin/bash


######## CHECK (system_info.sh -c)
if [ $1 == "check" ]
    then


    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_NETWORK_DEVICES_status=0


    ######## CHECK_NETWORK_DEVICES
    ######## IFCONFIG
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_NETWORK_DEVICES (# $IFCONFIG)" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT

    if [ ! -f "$IFCONFIG" ]
	then
	$PRINT "$MSG_MISSING_COMMAND $IFCONFIG" >> $OUTPUT
	$PRINT "$MSG_NEED_PACKAGE $IFCONFIG_package" >> $OUTPUT
	let CHECK_NETWORK_DEVICES_status=1

	else
	$IFCONFIG >> $OUTPUT
	check_rv_output CHECK_NETWORK_DEVICES_status
    fi

    $PRINTE "\n\n" >> $OUTPUT

fi
