#!/bin/bash


######## CHECK (system_info.sh -c)
if [ $1 == "check" ]
    then
    

    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_ARP_TABLE_status=0


    ######## CHECK_ARP_TABLE
    ######## ARP
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_ARP_TABLE (# $ARP $ARP_p)" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT

    if [ ! -f "$ARP" ]
	then
	$PRINT "$MSG_MISSING_COMMAND $ARP" >> $OUTPUT
	$PRINT "$MSG_NEED_PACKAGE $ARP_package" >> $OUTPUT
	let CHECK_ARP_TABLE_status=1

	else
	$ARP $ARP_p >> $OUTPUT
	check_rv_output CHECK_ARP_TABLE_status
    fi

    $PRINTE "\n\n" >> $OUTPUT

fi
