#!/bin/bash


######## INITIALIZATION (system_info.sh -i)
if [ "$1" == "init" ]
    then
    if [ -f "$WORKDIR/iptables_current" ]
        then 
        $RM $WORKDIR/iptables_current
    fi

    if [ -f "$WORKDIR/iptables_init" ]
	then
	$RM $WORKDIR/iptables_init
    fi

    $IPTABLESSAVE | $SED 's/.[0-9]*:[0-9]*.$/ /g' | $SED 's/^#.*/ /g' >$WORKDIR/iptables_init
    check_rv_output CHECK_IPTABLES_DIFF_status
    $PRINTE "$MSG_IPTABLES_DIFF_INIT"
fi


######## CHECK (system_info.sh -c)
if [ "$1" == "check" ]
    then


    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_IPTABLES_DIFF_status=0

	
    ######## IPTABLES-SAVE + "MAGIC" ;-)
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_IPTABLES_DIFF" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT

    if [[ ! -f "$IPTABLESSAVE" || ! -f "$SHA1SUM" || ! -f "$AWK" ]]
        then
        $PRINT "$MSG_MISSING_COMMAND $IPTABLESSAVE, $SHA1SUM, $AWK" >> $OUTPUT
        $PRINT "$MSG_NEED_PACKAGE $IPTABLESSAVE_package, $SHA1SUM_package, $AWK_package" >> $OUTPUT
	let CHECK_IPTABLES_DIFF_status=1

        else
        if [ -f "$WORKDIR/iptables_init" ]
	    then
	    iptables_sha1_current=`$IPTABLESSAVE | $SED 's/.[0-9]*:[0-9]*.$/ /g' | $SED 's/^#.*/ /g' >$WORKDIR/iptables_current; $SHA1SUM $WORKDIR/iptables_current | $AWK '{ print $1 }'`
	    check_rv_output CHECK_IPTABLES_DIFF_status
	    iptables_sha1_init=`$SHA1SUM < $CAT $WORKDIR/iptables_init | $AWK '{ print $1 }'`
	    check_rv_output CHECK_IPTABLES_DIFF_status
			
	    # if $route_sha1_current == $route_sha1_init -> OK else WARN
	    case $iptables_sha1_current in
	    $iptables_sha1_init)
		$PRINT "$MSG_IPTABLES_DIFF_UNCHANGED" >> $OUTPUT
		;;
	    *)
		$PRINT "$MSG_IPTABLES_DIFF_CHANGED" >> $OUTPUT
		;;
	    esac
	
						
	    else
	    $PRINT "$MSG_IPTABLES_DIFF_MISSING_INIT" >> $OUTPUT
	fi				
    fi

    $PRINTE "\n\n" >> $OUTPUT

fi
