#!/bin/bash


######## CONFIGURATION

# list of checked processes
# -------------------------
CHECK_RUNNING_PROCESSES_LIST="sshd
inetd"

######## CONFIGURATION


######## CHECK (system_info.sh -c)
if [ $1 == "check" ]
    then
    
    
    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_RUNNING_PROCESSES_status=0


    ################# CHECK_RUNNING_PROCESSES
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_RUNNING_PROCESSES" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT


    if [[ ! -f "$PS"  || ! -f "$GREP" || ! -f "$AWK" ]] 
	then
	$PRINT "$MSG_MISSING_COMMAND $PS, $GREP, $AWK" >> $OUTPUT
	$PRINT "$MSG_NEED_PACKAGE $PS_package, $GREP_package, $AWK_package" >> $OUTPUT
	let CHECK_RUNNING_PROCESSES_status=1

	else 
    
	for process in $CHECK_RUNNING_PROCESSES_LIST
	do
	    running=`$PS xa | $GREP $process | $GREP -v grep | $AWK '{ print $5 }' | $GREP -e $process`
	    check_rv_output CHECK_RUNNING_PROCESSES_status
	
	    if [ "$running" != "" ]
		then    
		$PRINT "$MSG_RUNNING_PROCESSES_RUNNING $process" >> $OUTPUT
		check_rv_output CHECK_RUNNING_PROCESSES_status
		else
		$PRINT "$MSG_RUNNING_PROCESSES_NOTRUNNING $process" >> $OUTPUT 
		check_rv_output CHECK_RUNNING_PROCESSES_status
	    fi

	done
    fi
    
    $PRINTE "\n\n" >> $OUTPUT

fi
