#!/bin/bash


######## CHECK (system_info.sh)
if [ $1 == "check" ]
    then


    ################# VARIABLES for CHECK of CHECKs :-)
    CHECK_VPN_IPSEC_status=0


    ######## CHECK_VPN_IPSEC
    ######## IPSEC
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    $PRINTE "| $MSG_VPN_IPSEC (# $IPSEC $IPSEC_p)" >> $OUTPUT
    $PRINT  "+--------------------------------------------------------------------------------->" >> $OUTPUT
    
    if [ ! -f "$IPSEC" ]
	then
	$PRINT "$MSG_MISSING_COMMAND $IPSEC" >> $OUTPUT
	$PRINT "$MSG_NEED_PACKAGE $IPSEC_package" >> $OUTPUT
	let CHECK_VPN_IPSEC_status=1

	else
	$IPSEC $IPSEC_p >> $OUTPUT
	check_rv_output CHECK_VPN_IPSEC_status
    fi
    
    $PRINTE "\n\n" >> $OUTPUT

fi
