#!/bin/bash
#
# SYSTEM_TOOLS_COMMANDS_debian
# ----------------------------
# Definicia prikazov a ciest k prikazom + nazvy balickov, ktore obsahuju tieto prikazy v distribucii Debian.
# Definition of commands and paths to commands + names of packages in which are these commands in Debian distribution.
#
# LALA 2009 -> lala (at) linuxor (dot) sk
#


# PRIKAZY				BALICEK
# COMMANDS				PACKAGE
# ---------------------------------------------
APTGET="/usr/bin/apt-get"		# apt
APTGET_package="apt"
ARP="/usr/sbin/arp"			# net-tools
ARP_p="-a"				# net-tools
ARP_package="net-tools"
AWK="/usr/bin/awk"			# mawk
AWK_package="mawk"
BASENAME="/usr/bin/basename"		# coreutils
BASENAME_package="coreutils"
BC="/usr/bin/bc"			# bc
BC_package="bc"
BZIP2="/bin/bzip2"			# bzip2
BZIP2_package="bzip2"
CAT="/bin/cat"				# coreutils
CAT_package="coretils"
CP="/bin/cp"				# coreutils
CP_package="coreutils"
DATE="/bin/date"			# coreutils
DATE_package="coreutils"
DD="/bin/dd"				# coreutils
DD_package="coreutils"
DF="/bin/df"				# coreutils
DF_p="-h -P -l -T"			# coreutils
DF_package="coreutils"
DIRNAME="/usr/bin/dirname"		# coreutils
DIRNAME_package="coreutils"
DPKG="/usr/bin/dpkg"			# dpkg
DPKG_package="dpkg"
DMESG="/bin/dmesg"			# util-linux
DMESG_package="util-linux"
FIND="/usr/bin/find"			# findutils
FIND_package="findutils"
FREE="/usr/bin/free"			# procps
FREE_p="-mto"				# procps
FREE_package="procps"
FRESHCLAM="/usr/bin/freshclam"		# clamav-freshclam
FRESHCLAM_p=""				# clamav-freshclam
FRESHCLAM_package="clamav-freshclam"
GPG="/usr/bin/gpg"			# gnupg
GPG_package="gnupg"
GREP="/bin/grep"			# grep
GREP_p=""				# grep
GREP_package="grep"
GZIP="/bin/gzip"			# gzip
GZIP_package="gzip"
IFCONFIG="/sbin/ifconfig"		# net-tools
IFCONFIG_package="net-tools"
IOSTAT="/usr/bin/iostat"		# sysstat
IOSTAT_p="-xd"				# sysstat
IOSTAT_package="sysstat"
IPSEC="/usr/local/sbin/ipsec"		# strongswan, openswan
IPSEC_p="auto --status"			# strongswan, openswan
IPSEC_package="strongswan, openswan"
IPTABLESSAVE="/sbin/iptables-save"	# iptables
IPTABLESSAVE_package="iptables"
LAST="/usr/bin/last"			# sysvinit-utils
LAST_package="sysvinit-utils"
LN="/bin/ln"				# coreutils
LN_package="coreutils"			
LS="/bin/ls"				# coreutils
LS_package="coreutils"
LSMOD="/bin/lsmod"			# module-init-tools
LSMOD_package="module-init-tools"
LVCREATE="/sbin/lvcreate"		# lvm2
LVCREATE_package="lvm2"
LVREMOVE="/sbin/lvremove"		# lvm2
LVMREMOVE_package="lvm2"
LVS="/sbin/lvs"				# lvm2
LVS_p="--units M -o +devices"		# lvm2
LVS_package="lvm2"
MAIL="/usr/bin/mail"			# mailutils, mailx
MAIL_package="mailutils, mailx"
MAILQ="/usr/bin/mailq"			# postfix, sendmail-bin, smail ...
MAILQ_package="postfix, sendmail-bin, smail ..."
MD5SUM="/usr/bin/md5sum"		# md5sum
MD5SUM_package="md5sum"
MKDIR="/bin/mkdir"			# coreutils
MKDIR_package="coreutils"
MKSWAP="/sbin/mkswap"			# util-linux
MKSWAP_package="utils-linux"
MOUNT="/bin/mount"			# mount
MOUNT_p=""				# mount
MOUNT_package="mount"
MPSTAT="/usr/bin/mpstat"		# sysstat
MPSTAT_p="-P ALL"			# sysstat
MPSTAT_package="sysstat"
NETSTAT="/bin/netstat"			# net-tools
NETSTAT_p="-tunpl"			# net-tools
NETSTAT_package="net-tools"	
NULL="/dev/null"			
PRINT="/bin/echo"			# coreutils
PRINT_package="coreutils"
PRINTE="/bin/echo -e"			# coreutils
PS="/bin/ps"				# procps
PS_p=""					# procps
PS_package="procps"
PVS="/sbin/pvs"				# lvm2
PVS_p="--units M"			# lvm2
PVS_package="lvm2"
READLINK="/bin/readlink"		# coreutils
READLINK_package="coreutils"
RESET="tput sgr0"			# ncurses-bin
RESET_package="ncurses-bin"
RM="/bin/rm"				# coreutils
RM_package="coreutils"
RMDIR="/bin/rmdir"			# coreutils
RMDIR_package="coreutils"
ROUTE="/sbin/route"			# net-tools
ROUTE_package="net-tools"
SED="/bin/sed"				# sed
SED_package="sed"
SHA1SUM="/usr/bin/sha1sum"		# coreutils
SHA1SUM_package="coreutils"
SORT="/usr/bin/sort"			# coreutils
SORT_PACKAGE="coreutils"
TAIL="/usr/bin/tail"			# coreutils
TAIL_package="coreutils"
TAR="/bin/tar"				# tar
TAR_package="tar"
TOUCH="/bin/touch"			# coreutils
TOUCH_package="coreutils"
UPTIME="/usr/bin/uptime"		# procps
UPTIME_package="procps"
W="/usr/bin/w"				# procps
W_package="procps"
WC="/usr/bin/wc"			# coreutils
WC_package="coreutils"
XM="/usr/sbin/xm"			# xen-utils-common
XM_package="xen-utils-common"
